### ISSUE TITLE
plt.xkcd()

### ISSUE THREAD

**Issue by danielfalbo** [javierramirezzayas/logically#2]
### Before Logically I used to draw logic circuits explicitly with SchemDraw, occasionally using `plt.xkcd()` as explained at the end of [this page](https://cdelker.bitbucket.io/SchemDraw/usage.html). I would really like to use it with Logically too! 

I tried to modify logic_gate_modules.py adding `plt.xkcd()` in the constructor just before `self.d = schem.Drawing(unit=.5)` but while trying to generate a circuit image I got this error: 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 74, in _draw
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1736, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/image.py", line 137, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2630, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/image.py", line 137, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/text.py", line 733, in draw
    ismath=ismath, mtext=mtext)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 547, in draw_text
    self._draw_text_as_path(gc, x, y, s, prop, angle, ismath)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patheffects.py", line 142, in _draw_text_as_path
    angle, ismath)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 567, in _get_text_path_transform
    path = Path(verts, codes)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/path.py", line 130, in __init__
    "'vertices' must be a 2D list or array with shape Nx2")
ValueError: 'vertices' must be a 2D list or array with shape Nx2`.

### Can you help me implement `plt.xkcd()` ? Thanks in advance :)

**Comment by javierramirezzayas** [comment]
Hi danielfalbo. It's a pleasure to know that Logically is useful for you. I did an inspection of the code and found out that substituting `out_lbl = "\n" + stack[0]` with `out_lbl =  stack[0]` on logic_gates_drawer.py fixes the issue. I do not know the exact reason why but it has to do with matplotlib trying to add "\n" on a drawing when using xkdc().

**Comment by danielfalbo** [comment]
It's working! :) Thanks
